code --install-extension formulahendry.code-runner
code --install-extension foxundermoon.shell-format
code --install-extension github.github-vscode-theme
code --install-extension github.remotehub
code --install-extension golang.go
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode.azure-repos
code --install-extension ms-vscode.remote-repositories
code --install-extension redhat.java
code --install-extension rust-lang.rust-analyzer
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
